### ISSUE TITLE
spinner freeze on Android device

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#10]
Hi @JoeyAndres ,
When I build your demo app and run it on a real android device spinner freeze and no animation available.
I talked about this page:
http://jandres-ionic.meteor.com/spinner

**Comment by cyclops24** [comment]
Hi @JoeyAndres,
Please label this issue to `native` too.

**Comment by cyclops24** [comment]
I test this issue on an android 5 device and it's OK.
I don't know why but it's still not working on my other android 4.2.1 devices.

**Comment by JoeyAndres** [comment]
I'm guessing because 4.2 was the last android that does not support css3 animation. 4.3 and onwards support it. What the code should've done is use javascript animation when it doesn't detect css3 animation feature. I just quickly scanned the code, this should be an easy fix.

http://caniuse.com/#search=animation

**Comment by cyclops24** [comment]
@JoeyAndres  Thanks for your replay. Based on your replay, I think maybe use some library like [modernizr](https://modernizr.com/) can fix this.

**Comment by JoeyAndres** [comment]
@cyclops24 Exactly. Was my thought too. The problem with that though is modernizr is relatively HUGE, when we only want to use one feature. My plan is to steal some code, and when another one of this arise in the future, use some meteor package to do the thing.

**Comment by cyclops24** [comment]
@JoeyAndres It's interesting for me that is original Ionic also have this issue or only meteoric version has this or maybe cordova version of meteor is outdate?
Because I read somewhere that newer version of Ionic fix css animation and support it.
Do you know anything about this??

**Comment by JoeyAndres** [comment]
That is interesting. I can't really tell which is the problem. Nick. W (the original author of meteoric) copied the whole spinnerController.js from version 0.9.x (somewhere close). By the looks of it, there have been some changes/fixes since then. I'll try to download many emulators from 4.2 onwards and test them.

**Comment by JoeyAndres** [comment]
@cyclops24 4.2 Emulator is not working well for me. I will not work on this issue until I can buy another old android phone so I can install 4.2.

**Comment by cyclops24** [comment]
@JoeyAndres What is the android emulator issue?? You can also test on [Genymotion](https://www.genymotion.com/).

**Comment by JoeyAndres** [comment]
@cyclops24 Lol, I used this 3 years ago in a software engineering course. I remember this being WAYYYYY FASTER. Thanks for reminding me.

**Comment by JoeyAndres** [comment]
@cyclops24 Nevermind, I'm using fedora 23. They only have ubuntu for linux.

**Comment by JoeyAndres** [comment]
@cyclops24 I copied ionic 1.2.4's code for this (line for line) and it still doesn't work. I

**Comment by JoeyAndres** [comment]
@cyclops24 The fix is now pushed. The main problem is 

http://caniuse.com/#search=requestAnimationFrame

meaning, a polyfill for that feature is needed, which is what was done.

The only problem is:

> Each spinner uses SVG with SMIL animations, however, the Android spinner also uses JavaScript
> so it also works on Android 4.0-4.3. Additionally, each spinner can be styled with CSS,
> and scaled to any size.

Meaning, spinners for android is only the android spinner.

Should this be closed? https://github.com/JoeyAndres/meteor-ionic/issues/7 

Tell me if it is working or now.
