### ISSUE TITLE
Add support for FlowRouter

### ISSUE THREAD

**Issue by skirunman** [JoeyAndres/meteor-ionic#49]
[FlowRouter](https://github.com/kadirahq/flow-router) is now the recommended router by MDG and IronRouter has limited support going forward. Therefore, it would be awesome if you could integrate in support for FlowRouter. It looks like there is already a port to FlowRouter https://github.com/txs/meteor-wecare-ionic-flow/ and this was previously discussed https://github.com/meteoric/meteor-ionic/issues/199

I'd be willing to donate a small $ amount to make it happen and have you support it going forward. You could probably combine efforts with @txs.

**Comment by JoeyAndres** [comment]
@skirunman For sure.

**Comment by txs** [comment]
@skirunman  txs here! Do you have issue with my package? I'm here to help

**Comment by JoeyAndres** [comment]
@skirunman @txs I'll let you too sort this out before I start this thing.

**Comment by skirunman** [comment]
@txs No issue with you package. it looks like @JoeyAndres was adding new features though and looking to possibly even integrate in some Ionic 2 features. Would be awesome to have one supported package going forward that supports FlowRouter.

**Comment by txs** [comment]
@JoeyAndres  Cool! Please work on ionic2. If you need me to do the FlowRouter part. I can help. I'm recently playing with framework7. So might have a package about that.

**Comment by DanielDornhardt** [comment]
Hi everybody,

I've started on a branch going for router-independence here: https://github.com/DanielDornhardt/meteor-ionic/tree/flow-integration (make sure to checkout the flow-integration branch!)

I'm trying to use https://github.com/nicolaslopezj/meteor-router-layer as a basic abstraction layer of both Flow-Router and Iron-Router.

The good news: I think this is good enough now for _my_ uses at the moment, but there are still some issues:

## Problems / differences:
- I "broke" the menu bar animation when using Iron:Router (it was sliding back and forth happily in the original JoeyAndres - Version)
- There's a new system added to dynamically render the navBar when using Flow-Router:

You need to pass on a navBarTemplateName and the data you want to pass on to the ionNavBar like this:

```
{{>ionNavBar class="bar-dark" transition="none" navBarTemplateName=getNavBarTemplateName navBarData=this}}
{{/ionNavBar}}
```

`navBarTemplateName` should be a helper (or variable) returning/containing the name of the template to render. Mine looks like this:

```
Template.layout.helpers({
    getNavBarTemplateName: function() {
        let navBarTemplateName = '' + this.area() + 'NavBar'
        return navBarTemplateName
    }
})
```
- So you just add a string to your area name and add two templates into you page template instead of one:

```
<template name="exampleNavBar">
   <h1 class="title">{{title}}</h1>
</template>

<template name="example">
    <h1>Hello Flow-Router Example</h1>
</template>

```

---

There's a problem with the ionNavBar- and content-area (ionNavView) - transitions as well - both don't seem to work right with my first, hacky solution.

Therefore I added two new attributes to `ionNavBar` and `ionNavView`: if you add `transition="none"` to either one, the transitions for them will be disabled and they'll stay where they are.

See the first problem above though: The ionNavBar - animation for Iron-Router is always off / broken at the moment anyways, and for Flow-Router the animation doesn't look right because of the difference in how it's content is rendered (you can see the changed / new menu title fly out and in again, which doesn't seem right to me!)

The whole layout template for me now looks like this:

```

<template name="layout">
    {{#ionBody}}
        {{#ionSideMenuContainer side="left"}}
            {{#ionSideMenus}}
                {{#ionSideMenu side="left" exposeAsideWhen="large"}}
                    {{> sideMenu }}
                {{/ionSideMenu}}
            {{/ionSideMenus}}
            {{#ionSideMenuContent}}
                {{#ionNavBar class="bar-dark" transition="none" navBarTemplateName=getNavBarTemplateName navBarData=this}}
                {{/ionNavBar}}

                {{#ionNavView transition="none"}}
                    {{#ionView class="content-container" }}
                        {{#ionContent class="padding"}}
                            {{> Template.dynamic template=area }}
                        {{/ionContent}}
                    {{/ionView}}
                {{/ionNavView}}
            {{/ionSideMenuContent}}
        {{/ionSideMenuContainer}}
    {{/ionBody}}

</template>

<template name="sideMenu">
    <div class="bar bar-header bar-dark nav-header-menu-left padding">
        Example Flow-Router-Meteoric-App
    </div>
    {{#ionContent class="sideMenu"}}
        {{#ionList}}
            {{#each testRoutes}}
                <a class="item item-icon-left" href={{path}} data-ion-menu-close>
                    <h2>{{title}}</h2>
                    {{> ionIcon icon="ios-arrow-right" }}
                </a>
            {{/each}}
        {{/ionList}}
    {{/ionContent}}
</template>
```

---

And last but not least: I didn't update the documentation yet.

I'd love to see this integrated one way or another and to have a unified, maintained meteoric fork ongoing from here on to be able to pull in updates and fixes from others as well.

What does everybody think about this so far?

**Comment by txs** [comment]
Cool

**Comment by cyclops24** [comment]
I see this about support multiple routers in Meteor packages:
https://github.com/nicolaslopezj/meteor-router-layer
Maybe useful and simplify FlowRouter support. :wink:

**Comment by txs** [comment]
Thanks for the info. Currently busy! Will help soon :D

2016-04-06 11:20 GMT+08:00 Ba Ba K notifications@github.com:
